FROM node:18 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --silent

COPY . .

# Modify the API URL in App.js to use the relative path
RUN sed -i 's|http://localhost:5000/run|/api/run|g' src/App.js

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
